In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Coffee Shop Sales.xlsx')
df.head().T

,0,1,2,3,4
transaction_id,1,2,3,4,5
transaction_date,2023-01-01 00:00:00,2023-01-01 00:00:00,2023-01-01 00:00:00,2023-01-01 00:00:00,2023-01-01 00:00:00
transaction_time,07:06:11,07:08:56,07:14:04,07:20:24,07:22:41
transaction_qty,2,2,2,1,2
store_id,5,5,5,5,5
store_location,Lower Manhattan,Lower Manhattan,Lower Manhattan,Lower Manhattan,Lower Manhattan
product_id,32,57,59,22,57
unit_price,3.0,3.1,4.5,2.0,3.1
product_category,Coffee,Tea,Drinking Chocolate,Coffee,Tea
product_type,Gourmet brewed coffee,Brewed Chai tea,Hot chocolate,Drip coffee,Brewed Chai tea
product_detail,Ethiopia Rg,Spicy Eye Opener Chai Lg,Dark chocolate Lg,Our Old Time Diner Blend Sm,Spicy Eye Opener Chai Lg

In [3]:
print(df.isnull().sum())

transaction_id      0
transaction_date    0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[ns]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 12.5+ MB

---
Noticed:
1. transaction_time  -> currently object -> need in time
2. no column for sales -> create one by -> transaction_qty * unit_price

In [7]:
df['transaction_time'] = df['transaction_time'].astype(str)
df['transaction_time'] = pd.to_timedelta(df['transaction_time'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[ns]
 2   transaction_time  149116 non-null  timedelta64[ns]
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(4), timedelta64[ns](1)
memory usage: 12.5+ MB

In [9]:
df['sales'] = df['transaction_qty'] * df['unit_price']
df['datetime'] = df['transaction_date'] + df['transaction_time']
df.head().T

,0,1,2,3,4
transaction_id,1,2,3,4,5
transaction_date,2023-01-01 00:00:00,2023-01-01 00:00:00,2023-01-01 00:00:00,2023-01-01 00:00:00,2023-01-01 00:00:00
transaction_time,0 days 07:06:11,0 days 07:08:56,0 days 07:14:04,0 days 07:20:24,0 days 07:22:41
transaction_qty,2,2,2,1,2
store_id,5,5,5,5,5
store_location,Lower Manhattan,Lower Manhattan,Lower Manhattan,Lower Manhattan,Lower Manhattan
product_id,32,57,59,22,57
unit_price,3.0,3.1,4.5,2.0,3.1
product_category,Coffee,Tea,Drinking Chocolate,Coffee,Tea
product_type,Gourmet brewed coffee,Brewed Chai tea,Hot chocolate,Drip coffee,Brewed Chai tea
product_detail,Ethiopia Rg,Spicy Eye Opener Chai Lg,Dark chocolate Lg,Our Old Time Diner Blend Sm,Spicy Eye Opener Chai Lg
sales,6.0,6.2,9.0,2.0,6.2
datetime,2023-01-01 07:06:11,2023-01-01 07:08:56,2023-01-01 07:14:04,2023-01-01 07:20:24,2023-01-01 07:22:41

In [10]:
df.describe()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,product_id,unit_price,sales,datetime
count,149116.000000,149116,149116,149116.000000,149116.000000,149116.000000,149116.000000,149116.000000,149116
mean,74737.371872,2023-04-15 11:50:32.173609984,0 days 12:14:15.815794415,1.438276,5.342063,47.918607,3.382219,4.686367,2023-04-16 00:04:47.989404160
min,1.000000,2023-01-01 00:00:00,0 days 06:00:00,1.000000,3.000000,1.000000,0.800000,0.800000,2023-01-01 07:06:11
25%,37335.750000,2023-03-06 00:00:00,0 days 09:05:10.500000,1.000000,3.000000,33.000000,2.500000,3.000000,2023-03-06 13:37:08
50%,74727.500000,2023-04-24 00:00:00,0 days 11:15:28,1.000000,5.000000,47.000000,3.000000,3.750000,2023-04-24 08:24:32.500000
75%,112094.250000,2023-05-30 00:00:00,0 days 15:25:57,2.000000,8.000000,60.000000,3.750000,6.000000,2023-05-30 07:16:13
max,149456.000000,2023-06-30 00:00:00,0 days 20:59:32,8.000000,8.000000,87.000000,45.000000,360.000000,2023-06-30 20:57:19
std,43153.600016,NaN,0 days 03:45:57.901686173,0.542509,2.074241,17.930020,2.658723,4.227099,NaN

Import New Table to MS SQL Server

In [12]:
!pip install sqlalchemy pyodbc pandas
import sqlalchemy as sa
import urllib

Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: pyodbc in c:\programdata\anaconda3\lib\site-packages (5.1.0)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [14]:
# 1. Define your connection parameters
server = 'localhost'
database = 'coffee_shop_sales'
table_name = 'sales'

# 2. Build the connection string
params = urllib.parse.quote_plus(
    f'DRIVER={{ODBC Driver 17 for SQL Server}};'
    f'SERVER={server};'
    f'DATABASE={database};'
    f'Trusted_Connection=yes;'
)

# 3. Create the SQLAlchemy engine
engine = sa.create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# 4. Upload the DataFrame
try:
    df.to_sql(table_name, con=engine, index=False, if_exists='replace')
    print(f"Successfully imported {len(df)} rows into table '{table_name}'.")
except Exception as e:
    print("Error occurred: ", e)

C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\sql.py:1636: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())
C:\Users\Atharva's HP\AppData\Local\Temp\ipykernel_24780\2847163841.py:19: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql(table_name, con=engine, index=False, if_exists='replace')

Successfully imported 149116 rows into table 'sales'.